In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({
    '색상': ['빨강', '파랑', '초록', '빨강', '초록'],
    '가격': [1000, 1500, 2000, 1200, 1800]
})
display(df)

encoder = OneHotEncoder(sparse_output=False) # sparse_output=False 반환값을 numpy타입, True 행렬타입(판다스 호환 안됨)
result = encoder.fit_transform(df[['색상']])
# 인코딩 결과를 파생변수로 추가
df[['색상_빨강', '색상_파랑', '색상_초록']] = result

display(df)

   색상    가격
0  빨강  1000
1  파랑  1500
2  초록  2000
3  빨강  1200
4  초록  1800

   색상    가격  색상_빨강  색상_파랑  색상_초록
0  빨강  1000    1.0    0.0    0.0
1  파랑  1500    0.0    0.0    1.0
2  초록  2000    0.0    1.0    0.0
3  빨강  1200    1.0    0.0    0.0
4  초록  1800    0.0    1.0    0.0

In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({
    '만족도': ['높음', '낮음', '보통', '높음', '보통'],
    '가격': [1000, 1500, 2000, 1200, 1800]
})
display(df)

encoder = OrdinalEncoder(
    categories=[['낮음', '보통', '높음']]
)
# 인코딩 후 파생변수 생성
df['만족도_인코딩'] = encoder.fit_transform(df[['만족도']])

display(df)

  만족도    가격
0  높음  1000
1  낮음  1500
2  보통  2000
3  높음  1200
4  보통  1800

  만족도    가격  만족도_인코딩
0  높음  1000      2.0
1  낮음  1500      0.0
2  보통  2000      1.0
3  높음  1200      2.0
4  보통  1800      1.0

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    '길이': [30, 35, 40, 45, 50],
    '무게': [300, 350, 400, 450, 500],
    '종류': ['Bream', 'Smelt', 'Bream', 'Smelt', 'Bream']
})
display(df)

encoder = LabelEncoder()
# 정답 열을 숫자로 변환하여 파생변수 생성
df['종류_인코딩'] = encoder.fit_transform(df['종류'])

display(df)

   길이   무게     종류
0  30  300  Bream
1  35  350  Smelt
2  40  400  Bream
3  45  450  Smelt
4  50  500  Bream

   길이   무게     종류  종류_인코딩
0  30  300  Bream       0
1  35  350  Smelt       1
2  40  400  Bream       0
3  45  450  Smelt       1
4  50  500  Bream       0