In [1]:
import pandas as pd

df = pd.DataFrame({
    "이름": ["철수", "영희"],
    "국어": [80, 90],
    "영어": [70, 95],
    "수학": [90, 85]
})

display(df)

   이름  국어  영어  수학
0  철수  80  70  90
1  영희  90  95  85

In [2]:
df_melt = df.melt(
    id_vars="이름",       # 그대로 유지할 열, 이름은 각 행의 대상을 구분하기 위해 그대로 놔둔다
    var_name="과목",      # 기존 열 이름을 저장할 열
    value_name="점수"     # 기존 열의 값을 저장할 열
)

display(df_melt)

   이름  과목  점수
0  철수  국어  80
1  영희  국어  90
2  철수  영어  70
3  영희  영어  95
4  철수  수학  90
5  영희  수학  85

In [3]:
df = pd.DataFrame({
    "상품": ["노트북", "모니터", "키보드"],
    "1월": [100, 80, 50],
    "2월": [120, 90, 60],
    "3월": [150, 100, 70]
})

display(df)

    상품   1월   2월   3월
0  노트북  100  120  150
1  모니터   80   90  100
2  키보드   50   60   70

In [4]:
df_melt = df.melt(
    id_vars="상품",
    var_name="월",
    value_name="매출"
)

display(df_melt)

    상품   월   매출
0  노트북  1월  100
1  모니터  1월   80
2  키보드  1월   50
3  노트북  2월  120
4  모니터  2월   90
5  키보드  2월   60
6  노트북  3월  150
7  모니터  3월  100
8  키보드  3월   70

In [5]:
import pandas as pd

df = pd.DataFrame({
    "이름": ["철수", "철수", "철수", "영희", "영희", "영희"],
    "과목": ["국어", "영어", "수학", "국어", "영어", "수학"],
    "점수": [80, 70, 90, 90, 95, 85]
})

display(df)

   이름  과목  점수
0  철수  국어  80
1  철수  영어  70
2  철수  수학  90
3  영희  국어  90
4  영희  영어  95
5  영희  수학  85

In [6]:
df_pivot = df.pivot(
    index="이름",      # 행으로 사용할 열 -> 
    columns="과목",    # 새로운 열이 될 열 -> 과목열의 값들을 열이름으로
    values="점수"      # 실제 데이터 -> 새로 생성된 열의 값에 사용
)

display(df_pivot)

과목  국어  수학  영어
이름
영희  90  85  95
철수  80  90  70

In [7]:
df = pd.DataFrame({
    "이름": ["철수", "철수", "철수", "철수", "영희", "영희", "영희"],
    "과목": ["국어", "국어", "영어", "수학", "국어", "영어", "수학"],
    "점수": [80, 50, 70, 90, 90, 95, 85]
})

display(df)

   이름  과목  점수
0  철수  국어  80
1  철수  국어  50
2  철수  영어  70
3  철수  수학  90
4  영희  국어  90
5  영희  영어  95
6  영희  수학  85

In [8]:
# error -> 철수의 국어값이 80, 50 두객의 값이 되어 에러발생 
# ValueError: Index contains duplicate entries, cannot reshape

df_pivot = df.pivot(
    index="이름",      # 행으로 사용할 열
    columns="과목",    # 새로운 열이 될 열
    values="점수"      # 실제 데이터
)

display(df_pivot)

ValueError: Index contains duplicate entries, cannot reshape

In [9]:
# error -> 철수의 국어값이 80, 50 두객의 값이 되어 에러발생 
df_pivot = df.pivot_table(
    index="이름",      # 행으로 사용할 열
    columns="과목",    # 새로운 열이 될 열
    values="점수",      # 실제 데이터
    aggfunc="mean"     # 중복되는 값들에 사용될 집계함수
)

display(df_pivot)

과목    국어    수학    영어
이름
영희  90.0  85.0  95.0
철수  65.0  90.0  70.0

In [10]:
df_pivot = df.pivot_table(
    index="지점",       # 행
    columns="상품",     # 열
    values="매출",      # 계산할 값
    aggfunc="sum"       # 중복된 값을 합산
)

display(df_pivot)

# 평균
df.pivot_table(
    index="지점",
    columns="상품",
    values="매출",
    aggfunc="mean"
)

# 합계
df.pivot_table(
    index="지점",
    columns="상품",
    values="매출",
    aggfunc="sum"
)

# 데이터 개수
df.pivot_table(
    index="지점",
    columns="상품",
    values="매출",
    aggfunc="count"
)

KeyError: '매출'