In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# 1. 데이터 생성
df = pd.DataFrame({
    "키(cm)": [160, 170, 180],
    "연봉(원)": [50_000_000, 60_000_000, 80_000_000],
    "나이(세)": [30, 40, 50]
})

display(df)


# ==================================================
# 2. 직접 표준화 (Scikit-learn 사용 X)
# ==================================================

# 평균 계산
mean = df.mean()

# 모집단 표준편차 계산
std = df.std(ddof=0)

# 표준화
df_scaled = (df - mean) / std

display(df_scaled)


# ==================================================
# 3. Scikit-learn StandardScaler 사용
# ==================================================

scaler = StandardScaler()

df_scaled = scaler.fit_transform(df)

df_scaled = pd.DataFrame(
    df_scaled,
    columns=df.columns
)

display(df_scaled)

   키(cm)     연봉(원)  나이(세)
0    160  50000000     30
1    170  60000000     40
2    180  80000000     50

      키(cm)     연봉(원)     나이(세)
0 -1.224745 -1.069045 -1.224745
1  0.000000 -0.267261  0.000000
2  1.224745  1.336306  1.224745

      키(cm)     연봉(원)     나이(세)
0 -1.224745 -1.069045 -1.224745
1  0.000000 -0.267261  0.000000
2  1.224745  1.336306  1.224745

In [4]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MinMaxScaler


df = pd.DataFrame({
    "키(cm)": [160, 170, 180],
    "연봉(원)": [50_000_000, 60_000_000, 80_000_000],
    "나이(세)": [30, 40, 50]
})

display(df)


# --------------------------------------------------
# 1. 표준화(StandardScaler)
# 평균 → 0
# 표준편차 → 1
# --------------------------------------------------
print('1. 표준화(StandardScaler)')
scaler = StandardScaler()

df_standard = scaler.fit_transform(df)

df_standard = pd.DataFrame(
    df_standard,
    columns=df.columns
)

display(df_standard)


# --------------------------------------------------
# 2. 로버스트 스케일링(RobustScaler)
# 중앙값 → 0
# IQR을 기준으로 변환
# --------------------------------------------------
print('2. 로버스트 스케일링(RobustScaler)')
scaler = RobustScaler()

df_robust = scaler.fit_transform(df)

df_robust = pd.DataFrame(
    df_robust,
    columns=df.columns
)

display(df_robust)


# --------------------------------------------------
# 3. 정규화(MinMaxScaler)
# 최솟값 → 0
# 최댓값 → 1
# --------------------------------------------------
print('3. 정규화(MinMaxScaler)')
scaler = MinMaxScaler()

df_minmax = scaler.fit_transform(df)

df_minmax = pd.DataFrame(
    df_minmax,
    columns=df.columns
)

display(df_minmax)

   키(cm)     연봉(원)  나이(세)
0    160  50000000     30
1    170  60000000     40
2    180  80000000     50

1. 표준화(StandardScaler)

      키(cm)     연봉(원)     나이(세)
0 -1.224745 -1.069045 -1.224745
1  0.000000 -0.267261  0.000000
2  1.224745  1.336306  1.224745

2. 로버스트 스케일링(RobustScaler)

   키(cm)     연봉(원)  나이(세)
0   -1.0 -0.666667   -1.0
1    0.0  0.000000    0.0
2    1.0  1.333333    1.0

3. 정규화(MinMaxScaler)

   키(cm)     연봉(원)  나이(세)
0    0.0  0.000000    0.0
1    0.5  0.333333    0.5
2    1.0  1.000000    1.0